### ISSUE TITLE
Conflicting source-package definitions silently merged?

### ISSUE THREAD

**Issue by marvin2k** [rock-core/autoproj#112]
Hi,

I observe a confusing autoproj behavior.

The [25-release.yml][1] of the "entern" buildconf defines the package "external/lemon" in the following way:

```yml
- external/lemon:
    mode: 1
    no_subdirectory: false
    archive_dir:
    url: http://lemon.cs.elte.hu/pub/sources/lemon-1.3.tar.gz
```

but in "rock-core", the current [source.yml][2] defines it differently, like so:

```yml
    - external/lemon:
      type: archive
      url: http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
      update_cached_file: false
      patches:
            - $AUTOPROJ_SOURCE_DIR/patches/lemon_cmake_policy.patch
```

The mentioning in the "25-release.yml" is observed to have precedence.

Now the confusing part: The "patches:" section of the second "sources.yml" is added to the definition of the 1.3 release and does hence not apply. The build fails. Deleting the "patches:" entry in the "source.yml" fixes the build by successfully installing the 1.3 release.

This does not look like intended behavior? If files of the private entern buildconf might help to clarify the situation I will see what I can do ;-)

[1]: https://git.hb.dfki.de/entern/buildconf/blob/master/overrides.d/25-release.yml#L460
[2]: https://github.com/rock-core/rock-package_set/blob/master/source.yml#L260

**Comment by doudou** [comment]
If you have a 25-release.yml, it looks like you selected a release, which takes precedence.

Now, one question is why rock-core does not match the definition. In addition to pinning the packages, the release file should also have pinned the package sets. Could you verify that ? Would you have used `autoproj reset` in a way that pins packages and not package sets ?

**Comment by marvin2k** [comment]
I just bootstrapped the named entern buildconf, never actively selected any release or called anything but `amake smth`.

How do I verify that the package set is pinned?

**Comment by doudou** [comment]
> the named entern buildconf

I did not notice that ... Did not read the message properly. That would be the most likely hypothesis then: somebody is branches with releases in your buildconf, or you are supposed to bootstrap it with a tag=<name_of_rock_release>. In any case, this really does not look like an autoproj bug.

> How do I verify that the package set is pinned?

There's actually no way to query that within autoproj show :( Grep for pkg_set: in the overrides.d folder.

**Comment by marvin2k** [comment]
Ok. Just for completeness: The head of the 25-release.yml looks like this:

```yml
---
- pkg_set:github:/orocos-toolchain/autoproj.git:
    tag: rock-15.05
    branch: rock-15.05
    commit: 
- pkg_set:github:/rock-core/package_set.git:
    tag: rock-15.05
    branch: rock-15.05
    commit: 
- pkg_set:github:/rock-core/rock-package_set.git:
    branch: master
    commit: 
```

Which definitely looks like mixing. I would have naively expected that different entries of the yaml-maps with identical keys overwrite each other, instead of merging their content.

Closing the issue.
