### ISSUE TITLE
Autoproj v1.13.3 bootstrap script error when bootstraping Rock buildconf

### ISSUE THREAD

**Issue by Rauldg** [rock-core/autoproj#141]
These are the steps I have followed so far:

`wget https://raw.githubusercontent.com/rock-core/autoproj/v1.13.3/bin/autoproj_bootstrap`

`ruby autoproj_bootstrap git git@github.com:rock-core/buildconf.git`

This is the response:

`autoproj: installing a proper Ruby environment (this can take a long time)
failed: there is no osdeps definition for ruby23 (search tree: ruby->ruby23)`

I guess that some entry like the ones for ruby20 at line 2918 of the bootstrap script is missing for ruby23 so I tried with these lines (I am using Ubuntu 16.04)

```
ruby23:
  ubuntu:
    '16.04':
    - ruby
    - ruby-dev
    - rake
    - rubygems-integration
    default: ignore
  default: ignore
```
That takes me to the following error:

`
autoproj: installing a proper Ruby environment (this can take a long time)
autoproj: installing autoproj and its dependencies (this can take a long time)
    installing/updating RubyGems dependencies: autobuild ~>1.9.0
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement ["/home/dfki.uni-bremen.de/rdominguez"]
ERROR: failed to run /usr/bin/ruby2.3 -S gem2.3 install --no-user-install --no-format-executable --no-rdoc --no-ri autobuild -v ~>1.9.0
ERROR: command output is:
`
