### ISSUE TITLE
autoproj's osdeps system should fallback to the global default: entry if there are none in an os-specific part.

### ISSUE THREAD

**Issue by doudou** [rock-core/autoproj#15]
A global default: entry is meant to be useful for any OS and any version (typically, by using a non-os-specific package manager). Autoproj should allow falling back to it instead of requiring to copy/paste the entry in the OS-specific parts.

For instance,:

```
ubuntu:
   '14.04': a_debian_package
default:
   - gem: a_gem_package
```

currently requires to do

```
ubuntu:
   '14.04': a_debian_package
  default:
     - gem: a_gem_package
default:
   - gem: a_gem_package
```
