### ISSUE TITLE
conflict in import of package set

### ISSUE THREAD

**Issue by annaborn** [rock-core/autoproj#30]
In case if some standalone package set is imported through source.yml and the same package set is included through autoproj/manifest, it results in endless loop in sorting of package sets by import order.

The following set up was producing this error:

In the project package set the 'rock_simulation', which is a standalone package set, was imported:

```
name: limes
imports:
    - github: rock-simulation/package_set
```

At the same time the 'rock_simulation' was added throught the manifest file:

```
package_sets:
  - github: rock-core/package_set 
  - github: rock-core/rock-package_set 
  - github: rock-simulation/package_set
  - spacegit: rock-dfki/package_set
  - dfkigit: limes/package_set
  - dfkigit: besman-rock/package_set  
  - spacegit: team-learning/package_set
```

In this case "autoproj update" command resulted in endless loop in gems/autoproj-1.12.4/lib/autoproj/ops/configuration.rb line 296:

```
def sort_package_sets_by_import_order(package_sets, root_pkg_set)
...
     sorted = Array.new
     while !queue.empty?
          pkg_set = queue.shift
          if pkg_set.imports.any? { |imported_set| !sorted.include?(imported_set) }
               queue.push(pkg_set)
          else
               sorted << pkg_set
          end
     end
...
end
```

Through the condition (s. configuration.rb line 292) the 'rock_simulation' was not added into 'queue' array. Therefore this package set never appears in the 'sorted' array. That results that the project package set, that imports 'rock_simulation', get pushed to queue all the time.

configuration.rb line 292:

```
def sort_package_sets_by_import_order(package_sets, root_pkg_set)
...
     queue = package_sets.find_all do |pkg_set|
          (!pkg_set.imports.empty? || !pkg_set.explicit?) && !(pkg_set == root_pkg_set)
     end
...
end
```
