### ISSUE TITLE
CA certificate update

### ISSUE THREAD

**Issue by ivan1993br** [rock-core/autoproj#309]
Hi all!

I have the following source package definition:

```yml
- nanopb:
    retry_count: 3
    type: archive
    url: https://jpa.kapsi.fi/nanopb/download/nanopb-0.3.9.2-linux-x86.tar.gz
```

On my first update try I had the following error:
```bash
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate))
```
Which was present because I did not have the updated CA certificates, so I had to install them, in ubuntu `ca-certificates`

My question is, does it make sense to have it added as dependency and always install/update it?

Thanks
