### ISSUE TITLE
[Question] How to automatically set up the default Python interpreter?

### ISSUE THREAD

**Issue by caioaamaral** [rock-core/autoproj#357]
Recently, I've started receiving the following question during `autoproj update <package>` calls: 

> ''Select the path to the python executable [/usr/bin/python3]''

I've already tried the following `config.yml` for my bootstrap:

```yaml
USE_PYTHON: true
python_executable: /usr/bin/python2

#PYTHONPATH: /usr/bin/python2 (seems not effective)
```

With `USE_PYTHON` and `python_executable`, I can skip the question successfully. But the interpreter seems to be messed up (it points to .autoproj/bin/python), breaking my cmake packages build as it  cannot find a valid python interpreter:

> CMake Error at /usr/share/cmake-3.10/Modules/FindPythonInterp.cmake:116 (list):   list GET given empty list

I did notice some recent updates here, so I just would like to know the current proper way to set up (in a noninteractive way) the default python interpreter for my autoproj workspace.
