### ISSUE TITLE
autoproj versions does not record branch properly

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#48]
I have an override in the overrides.d for base/types
```
overriden in main configuration
      branch: update_logging
      commit: 03ed628700601823e42ad3126a614c3b6952902e`
```

my actual HEAD is on master, but when I do 
`autoproj versions base/types`
I get
```
- base/types:
    branch: update_logging
    tag: 
    commit: 03ed628700601823e42ad3126a614c3b6952902e
```

the commitid is correct, but not the branch.
